### ISSUE TITLE
Elsa.Guides.DocumentApproval.WebApp Error

### ISSUE THREAD

**Issue by jortygu** [elsa-workflows/elsa-guides#2]
hi,
  when i run the Elsa.Guides.DocumentApproval.WebApp project ,i got below error,is there something wrong?
 ```
UnparsableValueException: The value string does not match the required number from the format string "D". Value being parsed: '^PT01S'. (^ indicates error position.)
 ```

**Comment by sniperwolfpk5** [comment]
Yes I got same error. You will find this setting in appsettings.js file
Change it to like
` "BackgroundRunner": {
      "SweepInterval": "0:00:00:10"
    }`

**Comment by sfmskywalker** [comment]
@sniperwolfpk5 is correct - thanks!
