### ISSUE TITLE
Dashboard not Working

### ISSUE THREAD

**Issue by cmoussalli** [elsa-workflows/elsa-guides#6]
I'm trying to get this thing up and running, but with no luck.
I'm not sure is it a missing documentation issue or hosting config error.
I have tried both "/" & "/elsa/home" paths with no luck, just a 500 error :(

**Comment by ThreeLambs** [comment]
I fallow the docs,  it's works well .i use sqlserver

**Comment by sfmskywalker** [comment]
The guides are being updated to Elsa 2 (in the `elsa-2.0` branch for now until Elsa 2.0 is released).
