### ISSUE TITLE
demo "Elsa.Guides.DocumentApproval.WebApp" post data then return 404

### ISSUE THREAD

**Issue by ThreeLambs** [elsa-workflows/elsa-guides#8]
Demo Elsa.Guides.DocumentApproval.WebApp

![wfw](https://user-images.githubusercontent.com/23123048/106421705-26946c80-6498-11eb-893f-24e378cc33e8.png)
![wfs](https://user-images.githubusercontent.com/23123048/106421721-2c8a4d80-6498-11eb-91f7-e42a40364c1a.png)
![wf](https://user-images.githubusercontent.com/23123048/106421730-314f0180-6498-11eb-9ca6-c1916cf00a57.png)

```
curl --location --request POST 'http://localhost:5000/documents' \
--header 'Content-Type: application/json' \
--data-raw '{
    "Id": "3",
    "Author": {
        "Name": "John",
        "Email": "john@gmail.com"
    },
    "Body": "This is sample document."
}'
```
it return `404`.

**Comment by sfmskywalker** [comment]
The guides are being updated to Elsa 2 (in the `elsa-2.0` branch for now until Elsa 2.0 is released).
